AUTHENTICATION, MAIN_MENU, SCHEDULE_DRIVING, INSTRUCTOR_MENU, STUDENT_MANAGE, \
STUDENT_MANAGE_ADD, STUDENT_MANAGE_REMOVE, EDIT_SCHEDULE, \
WAITING_TXT_FILE, WAITING_TEXT_SCHEDULE, WAITING_CANCEL_CONFIRMATION = range(11)